/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QSnaSzWmmOG
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Caudex } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { LaptopIcon } from "@radix-ui/react-icons";
import { TbShoppingCartDiscount } from "react-icons/tb";

export function Populars() {
  return (
    <main className="w-full">
      <section className="container mx-auto px-4 py-12 md:py-16 lg:py-20">
        <div className="mb-8 text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Explore Top Categories
          </h2>
          <p className="mt-3 text-gray-500 dark:text-gray-400 sm:mt-4">
            Browse through our most popular product categories.
          </p>
        </div>
        <div className="grid grid-cols-2 gap-6 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">
          <a
            className="group flex flex-col items-center justify-center gap-3 rounded-lg bg-gray-100 p-4 text-center transition-colors hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700"
            href="#"
          >
            <div className="h-12 w-12 flex items-center justify-center rounded-full bg-gray-200 group-hover:bg-gray-300 dark:bg-gray-700 dark:group-hover:bg-gray-600">
              <TbShoppingCartDiscount className="h-6 w-6 text-gray-500 group-hover:text-gray-600 dark:text-gray-400 dark:group-hover:text-gray-300" />
            </div>
            <span className="text-sm font-medium text-gray-800 group-hover:text-gray-900 dark:text-gray-200 dark:group-hover:text-gray-100">
              Clothing
            </span>
          </a>
          <a
            className="group flex flex-col items-center justify-center gap-3 rounded-lg bg-gray-100 p-4 text-center transition-colors hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700"
            href="#"
          >
            <div className="h-12 w-12 rounded-full bg-gray-200 group-hover:bg-gray-300 dark:bg-gray-700 dark:group-hover:bg-gray-600 flex items-center justify-center">
              <LaptopIcon className="h-6 w-6 text-gray-500 group-hover:text-gray-600 dark:text-gray-400 dark:group-hover:text-gray-300" />
            </div>
            <span className="text-sm font-medium text-gray-800 group-hover:text-gray-900 dark:text-gray-200 dark:group-hover:text-gray-100">
              Electronics
            </span>
          </a>
        </div>
      </section>
      <section className="container mx-auto px-4 py-12 md:py-16 lg:py-20">
        <div className="mb-8 text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Top Stores
          </h2>
          <p className="mt-3 text-gray-500 dark:text-gray-400 sm:mt-4">
            Check out the most popular stores on our platform.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          <div className="flex items-center justify-between rounded-lg bg-gray-100 p-4 transition-colors hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700">
            <div className="flex items-center gap-4">
              <div>
                <h3 className="text-lg font-medium text-gray-800 dark:text-gray-200">
                  Amazon
                </h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Largest online retailer
                </p>
              </div>
            </div>
            <Button size="sm">View Offers</Button>
          </div>
          <div className="flex items-center justify-between rounded-lg bg-gray-100 p-4 transition-colors hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700">
            <div className="flex items-center gap-4">
              <div>
                <h3 className="text-lg font-medium text-gray-800 dark:text-gray-200">
                  Walmart
                </h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Leading retail corporation
                </p>
              </div>
            </div>
            <Button size="sm">View Offers</Button>
          </div>
        </div>
      </section>
    </main>
  );
}
